server.port : 8082
spring:
  mail:
    host : smtp.gmail.com
    username: roginfaf@gmail.com
    password: mixwwfqynsyakdwg
    port: 587
    properties:
      mail :
        smtp:
          starttls:
            enable: true
          auth: true











             
